package com.example.util

data class Language(
    val name: String,
    val code: String
)

val plenxoLanguages = listOf(
    Language("Afrikaans", "af"), Language("Akan", "ak"), Language("Albanian", "sq"), Language("Amharic", "am"), 
    Language("Arabic", "ar"), Language("Armenian", "hy"), Language("Assamese", "as"), Language("Awadhi", "awa"), 
    Language("Aymara", "ay"), Language("Azerbaijani", "az"), Language("Balochi", "bal"), Language("Bambara", "bm"), 
    Language("Bashkir", "ba"), Language("Basque", "eu"), Language("Belarusian", "be"), Language("Bengali", "bn"), 
    Language("Bhojpuri", "bho"), Language("Bikol", "bik"), Language("Bislama", "bi"), Language("Bosnian", "bs"), 
    Language("Breton", "br"), Language("Bulgarian", "bg"), Language("Buriat", "bua"), Language("Burmese", "my"), 
    Language("Catalan", "ca"), Language("Cebuano", "ceb"), Language("Chagatai", "chg"), Language("Chamorro", "ch"), 
    Language("Chechen", "ce"), Language("Chichewa", "ny"), Language("Chinese (Simplified)", "zh"), 
    Language("Chinese (Traditional)", "zh-TW"), Language("Chukot", "ckt"), Language("Chuvash", "cv"), 
    Language("Cornish", "kw"), Language("Corsican", "co"), Language("Cree", "cr"), Language("Crimean Tatar", "crh"), 
    Language("Croatian", "hr"), Language("Czech", "cs"), Language("Danish", "da"), Language("Dargwa", "dar"), 
    Language("Dinka", "din"), Language("Divehi", "dv"), Language("Dogri", "doi"), Language("Dutch", "nl"), 
    Language("Dzongkha", "dz"), Language("English", "en"), Language("Erzya", "myv"), Language("Esperanto", "eo"), 
    Language("Estonian", "et"), Language("Ewe", "ee"), Language("Faroese", "fo"), Language("Fijian", "fj"), 
    Language("Filipino", "tl"), Language("Finnish", "fi"), Language("Fon", "fon"), Language("French", "fr"), 
    Language("Fulah", "ff"), Language("Galician", "gl"), Language("Ganda", "lug"), Language("Georgian", "ka"), 
    Language("German", "de"), Language("Gilbertese", "gil"), Language("Gondi", "gon"), Language("Greek", "el"), 
    Language("Guarani", "gn"), Language("Gujarati", "gu"), Language("Haitian", "ht"), Language("Hausa", "ha"), 
    Language("Hawaiian", "haw"), Language("Hebrew", "he"), Language("Herero", "hz"), Language("Hiligaynon", "hil"), 
    Language("Hindi", "hi"), Language("Hiri Motu", "ho"), Language("Hmong", "hmn"), Language("Hungarian", "hu"), 
    Language("Iban", "iba"), Language("Icelandic", "is"), Language("Ido", "io"), Language("Igbo", "ig"), 
    Language("Ilocano", "ilo"), Language("Indonesian", "id"), Language("Ingush", "inh"), Language("Interlingua", "ia"), 
    Language("Interlingue", "ie"), Language("Inuktitut", "iu"), Language("Inupiaq", "ik"), Language("Irish", "ga"), 
    Language("Italian", "it"), Language("Japanese", "ja"), Language("Javanese", "jv"), Language("Kabardian", "kbd"), 
    Language("Kalaallisut", "kl"), Language("Kannada", "kn"), Language("Kanuri", "kr"), Language("Kashmiri", "ks"), 
    Language("Kazakh", "kk"), Language("Khmer", "km"), Language("Kikuyu", "ki"), Language("Kinyarwanda", "rw"), 
    Language("Kirundi", "rn"), Language("Komi", "kv"), Language("Kongo", "kg"), Language("Konkani", "gom"), 
    Language("Korean", "ko"), Language("Kuanyama", "kj"), Language("Kurdish", "ku"), Language("Kyrgyz", "ky"), 
    Language("Lao", "lo"), Language("Latin", "la"), Language("Latvian", "lv"), Language("Limburgan", "li"), 
    Language("Lingala", "ln"), Language("Lithuanian", "lt"), Language("Luba-Katanga", "lu"), Language("Luxembourgish", "lb"), 
    Language("Macedonian", "mk"), Language("Maithili", "mai"), Language("Malagasy", "mg"), Language("Malay", "ms"), 
    Language("Malayalam", "ml"), Language("Maltese", "mt"), Language("Manx", "gv"), Language("Maori", "mi"), 
    Language("Marathi", "mr"), Language("Marshallese", "mh"), Language("Mongolian", "mn"), Language("Nauru", "na"), 
    Language("Navajo", "nv"), Language("Ndonga", "ng"), Language("Nepali", "ne"), Language("Northern Sami", "se"), 
    Language("Norwegian", "no"), Language("Norwegian Bokmål", "nb"), Language("Norwegian Nynorsk", "nn"), 
    Language("Nyanja", "ny"), Language("Occitan", "oc"), Language("Odia", "or"), Language("Ojibwa", "oj"), 
    Language("Oromo", "om"), Language("Ossetian", "os"), Language("Pali", "pi"), Language("Pashto", "ps"), 
    Language("Persian", "fa"), Language("Polish", "pl"), Language("Portuguese", "pt"), Language("Punjabi", "pa"), 
    Language("Quechua", "qu"), Language("Romansh", "rm"), Language("Romanian", "ro"), Language("Russian", "ru"), 
    Language("Samoan", "sm"), Language("Sango", "sg"), Language("Sanskrit", "sa"), Language("Sardinian", "sc"), 
    Language("Scottish Gaelic", "gd"), Language("Serbian", "sr"), Language("Shona", "sn"), Language("Sindhi", "sd"), 
    Language("Sinhala", "si"), Language("Slovak", "sk"), Language("Slovenian", "sl"), Language("Somali", "so"), 
    Language("Southern Sotho", "st"), Language("Spanish", "es"), Language("Sundanese", "su"), Language("Swahili", "sw"), 
    Language("Swati", "ss"), Language("Swedish", "sv"), Language("Tagalog", "tl"), Language("Tahitian", "ty"), 
    Language("Tajik", "tg"), Language("Tamil", "ta"), Language("Tatar", "tt"), Language("Telugu", "te"), 
    Language("Thai", "th"), Language("Tibetan", "bo"), Language("Tigrinya", "ti"), Language("Tonga", "to"), 
    Language("Tsonga", "ts"), Language("Tswana", "tn"), Language("Turkish", "tr"), Language("Turkmen", "tk"), 
    Language("Twi", "tw"), Language("Uighur", "ug"), Language("Ukrainian", "uk"), Language("Urdu", "ur"), 
    Language("Uzbek", "uz"), Language("Venda", "ve"), Language("Vietnamese", "vi"), Language("Volapük", "vo"), 
    Language("Walloon", "wa"), Language("Welsh", "cy"), Language("Western Frisian", "fy"), Language("Wolof", "wo"), 
    Language("Xhosa", "xh"), Language("Yiddish", "yi"), Language("Yoruba", "yo"), Language("Zhuang", "za"), 
    Language("Zulu", "zu")
)
